### ISSUE TITLE
Migrate from aap to makefile

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc/asciidoc-py3#83]
Split this from https://github.com/asciidoc/asciidoc-py3/issues/44#issuecomment-446304054 to allow me to better track this work, what's left, etc.

Currently, asciidoc "uses" the [A-A-P](http://www.a-a-p.org/), while is not really supported anymore, not in any distro distribution, python2 only, etc. Ideally, transition away from it to something more universal, like `make` as nothing that happens here is that unique.

The A-A-P was setup in the following way:

common.aap:
- [x] set global variable to be used in other *.aap scripts for version and release date (`$VERS` and `$DATE`) (Added variables to makefile in #54)

main.aap
- [x] vers: prints out the version and release date from `common.aap` (done in #54)
- [x] vers_update: writes the version variable from `common.aap` into `asciidoc.py`, `a2x.py`, and `configure.ac` (done in #54)
- [x] tags: delete the `tags` file and then run [ctags](https://linux.die.net/man/1/ctags) over `asciidoc.py`, `asciidocapi.py`, `tests/testasciidoc.py`
- [ ] docs: run `./doc/main.aap`
- [ ] website: run `./examples/website/main.aap`
- [ ] distribution: runs `vers_update`, `docs`, `website` and then does:
  * Runs autoconf
  * symlinks current directory into `asciidoc-$VERS`
  * creates a tar (named `asciidoc-$VERS.tar.gz`) from all files listed in `MANIFEST` file
  * checks if `zip` command exists, and if so creates a zip (named `asciidoc-$VERS.tar.gz`) using the previously created symlink directory
  * Removes the symlink directory
- [x] test: Runs `python ./asciidoc.py --doctest`, `python ./asciidocapi.py`, executes `./doc/main.aap test`, and then `python ./tests/testasciidoc.py run` if there are *.html files in `./tests/data`

./doc/main.aap:
- [ ] all: converts all of the .txt files to the appropriate format (html, man, pdf, epub, etc.) as well as generating out pdf files and the like for distribution
- [ ] clean: removes all generated files
- [x] spell: checks the spelling in the text files through [aspell](http://aspell.net/) using `./doc/asciidoc.dict` as a dictionary for it  (done in #81)
- [ ] clean_testfiles: Removes files generated for tests (uses a subset of what clean does, but does include *.png files)
- [ ] test: Runs `clean_testfiles` and then generates the output from running asciidoc on the files in ./doc

./examples/website/main.aap:
- [ ] all: runs asciidoc over the files in the directory, getting html generated files
- [ ] copy: deletes and then creates directory `~/webs/asciidoc` and then copies the files necessary for the website to that directory. Does execute `./main.aap distribution` as part of this to ensure all necessary files have been generated.
- [ ] clean: Deletes the generated web pages
- [x] spell: runs [aspell](http://aspell.net/) over files in directory (done in #81)

The actual installation steps of asciidoc have always been handled by the `Makefile.in` file.

While one could try and place individual makefiles in the root folder, in docs, in examples/website/ and then do stuff with includes or hierarchal make executes, getting the pathing working correctly (especially if wanting to do a make execute from root into a sub-folder, have to update the $pwd first, then change it back after done execution) and other stuff makes it (to me) not worth trying to maintain 3 different makefiles. My goal is to unify all parts listed above into one topfile Makefile that can be used to build, update, install all parts of asciidoc.

Commands under the the sub-directories (doc and website) will be prefixed with `doc_` and `website_` respectively. An example of this is `doc_spell` runs the spell for the doc files and `website_spell` runs the spell for website files. There may be a top-level command to run both of these (e.g. `make spell`).

**Comment by MasterOdin** [comment]
Closing this for now as it's not clear to me if anyone is even bothering with A-A-P with asciidoc and that I'm not totally convinced of the value of the remaining endpoints (make docs, make distribution). Will re-code into make if someone requests it.
